apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: weave-gitops
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2023-11-15T04:12:33Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/part-of: weave-gitops
    app.kubernetes.io/version: v0.36.0
    helm.sh/chart: weave-gitops-4.0.34
    helm.toolkit.fluxcd.io/name: weave-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
    weave.works/app: weave-gitops-oss
  name: weave-gitops
  namespace: flux-system
  resourceVersion: "539435"
  uid: b84b29fd-d88d-4a14-80bc-c39904f8a77b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: weave-gitops
      app.kubernetes.io/name: weave-gitops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        reloader.stakater.com/last-reloaded-from: '{"type":"SECRET","name":"cluster-user-auth","namespace":"flux-system","hash":"06ba2f0e0172e23e9e314fef767032e22be08740","containerRefs":["weave-gitops"],"observedAt":1700084558}'
        secret.reloader.stakater.com/reload: cluster-user-auth
      #creationTimestamp: null
      labels:
        app.kubernetes.io/instance: weave-gitops
        app.kubernetes.io/name: weave-gitops
        app.kubernetes.io/part-of: weave-gitops
        weave.works/app: weave-gitops-oss
    spec:
      containers:
      - args:
        - --log-level
        - info
        - --insecure
        - --enable-metrics
        - --metrics-address=:2112
        env:
        - name: WEAVE_GITOPS_FEATURE_TENANCY
          value: "true"
        - name: WEAVE_GITOPS_FEATURE_CLUSTER
          value: "false"
        image: ghcr.io/weaveworks/wego-app:v0.36.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: weave-gitops
        ports:
        - containerPort: 9001
          name: http
          protocol: TCP
        - containerPort: 2112
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: weave-gitops
      serviceAccountName: weave-gitops
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-15T04:12:57Z"
    lastUpdateTime: "2023-11-15T04:12:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-15T04:12:33Z"
    lastUpdateTime: "2023-11-15T21:42:42Z"
    message: ReplicaSet "weave-gitops-84dc898bbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
