ansible_become_pass: ENC[AES256_GCM,data:dhIKEYfC1Ocs7aPbYw==,iv:gPb08moPSL8UebNhLwW4ONsA6pbw7EVaQwBNJ4FsoBE=,tag:BgW65Qc0Y0nkeHWe2E5vHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzl9chqrgrzgan20c8judfay5h6ejeadjvjz66qq3jd7fxlvmfjs382c84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTlFyWTloeDVZZHpFWFk5
            Y3NKYTc1QVNRUnNtVHV0SEhMeVNtQzYzNkJjClN2Z1hmSlRXZlhHbDBQYkpkc0w0
            M0xkTksvVVlFc2VHK2dEVUZuUHhRUUEKLS0tIFZCWHAzSUVlWmptZlpHazA3M2M3
            ZkUyYnIraFZqK1hkMXVtUS9CUW0zOHcKJiFYKbg5uARNHBVnc4Aeu4evG/m8l0xR
            HH7n7pNW/uKv8bArP18tPGQHaQwwTccZSOctssj4DWFrAJENo06WEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-15T20:58:44Z"
    mac: ENC[AES256_GCM,data:kT8whAsIx5ioj93IM144nYHh/BfEUubOcocC8Y+XQjSzOUv2Gl8qZNEQ50xBgdAts/i78Nfb6xdzDHkJSUlKwQ6YUQ0tAxNp38VqucCKe85wnb8R0jIeuLYBszxaYr2zaiSddZGsW1qG/zhPV4mGJD/NTtVQPMgF1vX8m2Ay6xw=,iv:yuNQ0fWW3S4dr18Avl2K+2dzqqHz8CQDGqhTgPwjRxA=,tag:HiBrzBRAweI+IDW/hW4b0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
