apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: "authentik.roguestarr.com"
  namespace: authentik
spec:
  endpoints:
  - dnsName: "authentik.roguestarr.com"
    recordTTL: 180
    recordType: CNAME
    targets:
    - "traefik-ingress.example.com"
