apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:m4motFaoBpOEMWDufNSKvkMP31hFZV18,iv:xS6rqS9cHoxujdDaSAqQGJrTrvN3PGirH/JOzADD5to=,tag:J2rmKaN5PqxRTSawi0oHyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzl9chqrgrzgan20c8judfay5h6ejeadjvjz66qq3jd7fxlvmfjs382c84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STkyMkpaWE41SnYwbjlQ
            YlZWaWpLZWlPZW4yQmJweG9kV2plbXFuVFJrCmVERkpKNHpJSGk3eFhZalFEUWNY
            dXIrU2NPRXd0cUVJQjFPRG1ONHI4Q28KLS0tIHlyOWF1dlJnOHBWbHNqa25XaktU
            NHFFbDlhSXcvTktaclJKZnFpMEhnem8KutfAYv0aDg7btlSEQ5xULwNcSWFjvZPX
            e9I+Jm8pXQaXhsE9OAvoMtG4Sm/SM8eIokYH25T7+Lv+XAeOfmyPzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T23:47:33Z"
    mac: ENC[AES256_GCM,data:oO6ZXnz92cWK/DVkrpVbVoqkXPjX3KuBby58nrDGJVy2WxkYZBBhZJF7AHHpXzzTTQyt+5ghZRoUJk6sn0743UW59bHVrmSBYRBDUlsyVA9Ka66yzc83fHBJs0b6s0aOdWlIE+Q46vs1GsNkgbayMDevbQSvZNY+k3/Q3i1IO/0=,iv:UdDSbZZ765fI/wSw4A7VSMzzKWbIZRVBcdmD7lQnd6Y=,tag:jm/EwsuiqLzH1SbkTFHwyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
