apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Q5XEAHXDXAjs4ZPF,iv:IRGjvefqrsF0uhuGf5eFkeocET/z8J7BkzlhSh/Hfoc=,tag:PaLogPLxFuqLo1jnIY+muw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzl9chqrgrzgan20c8judfay5h6ejeadjvjz66qq3jd7fxlvmfjs382c84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K05tR2F6NHljWXltVEJF
            L0xwOTJiaFZwdzRhMFZQOGVhQm51Ync3ZmdjCmJvcWVrcmJvNmtHR2Mwc293YTd4
            RmZBcldzS0RwYWFSd0dRcVorTExoWjQKLS0tIDVGYUx3N1BkeDI0MnF0NHJZQ2tu
            ckhaSDZQQjB0U2hweW5yNTBQTzhkcTQKVGZwumViOsvm+y3WWukvxBsj0M8+/e9b
            fbTf1D8LgwijNw9AKglgScz0y7851e/pJNnV4FsXstCiewMhYILq8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T23:47:33Z"
    mac: ENC[AES256_GCM,data:UZSe+oemToP4+kw1gqr9Q0YAFlJ7zTI2C44masN0qG4iRAnCq5s08V/yngjqPNp/jzLdPaT2zG6/2YkJfl+Lr8rQpusQppafMI0vC0DIhhppBz0bB5s3MDFwjBH61dkiLuXOyDmBJpfy01B/vUC62ODV0qWOJz2s8BPPrSi7pVk=,iv:gRR96gesLFe2FQeLaRi1SqD0Y9NfAoHF02okrJcBJLk=,tag:gB1XgkW/z60OBUiG6FJyvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
